# Generated by Django 3.0.4 on 2021-04-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='your@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='your@email.com', max_length=254),
        ),
    ]
